<?php session_start(); ?>
<!DOCTYPE html>
<html>
<head>
  <title>Booklist</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" />
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <center>
	<?php include 'HeaderAndBackground.php'; ?>
        <h1>Booklist of The Faculty of Natural Science, Keele University</h1>
		<div class=result style="max-width:100%;height:auto;"></div>
		
		
		
    <?php include 'Footer2.php'; ?>
	</center>
</body>
<script>
/* table of booklist generated by ajax */
$(document).ready(function(){
  $.ajax({
	url:"booklist1.csv",
	dataType:"text",
	success:function(data) {
		var book_data = data.split(/\r?\n|\r/);
		var table_data = '<table class="table table-bordered table-striped">';
		for(var count = 0; count<book_data.length; count++) {
			var cell_data = book_data[count].split(",");
			table_data += '<tr>';
			for(var cell_count=0; cell_count<cell_data.length; cell_count++) {
				if(count === 0) {
					table_data += '<th>'+cell_data[cell_count]+'</th>';
				} 
				else {
						table_data += '<td>'+cell_data[cell_count]+'</td>';
				}
			} 
			/* generate a button accessing to display.php to display details of a single record */
			if (count === 0) {
				table_data += '<th>'+'Button'+'</th>';
			} else {
				textCount = count.toString();
				table_data += '<td>'+'<form action="display.php" method="GET"><button type="submit" name="row" value='+textCount+'>'+textCount+'</button></form>'+'</td>';
			}
			table_data += '</tr>';
		}
		table_data += '</table>';
		$('.result').html(table_data);
  }
  });
});




</script>
  
</html>